config/routes.rb
Rails.application.routes.draw do
  resources :price_alerts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/momo_box_sale_tx.rb
class MomoBoxSaleTx < ApplicationRecord
end

app/models/momo_listing.rb
class MomoListing < ApplicationRecord
end

app/models/price_alert.rb
class PriceAlert < ApplicationRecord
  require_dependency 'live_coin_watch'

  validates_presence_of %i[coin currency price]
  after_validation :format_codes

  # returns alert message if alert triggered, else nil
  def alert(current_price)
    self.last_price ||= 0
    return nil if last_price == 0 # first check

    if last_price < price && current_price >= price
      "#{coin_pair} >= #{price}"
    elsif last_price > price && current_price <= price
      "#{coin_pair} <= #{price}"
    else
      nil
    end
  end

  def coin_pair
    "#{coin}/#{currency}"
  end

  def get_current_price
    res = LiveCoinWatch.coins_single(coin, currency)
    res['rate'].to_f
  end

  def update_last_price!(price)
    self.update(last_price: price)
  end

  private

    def format_codes
      coin.upcase!
      currency.upcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/price_alerts_controller.rb
class PriceAlertsController < ApplicationController
  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD']

  before_action :set_price_alert, only: %i[ show edit update destroy ]

  # GET /price_alerts or /price_alerts.json
  def index
    @price_alerts = PriceAlert.all
  end

  # GET /price_alerts/1 or /price_alerts/1.json
  def show
  end

  # GET /price_alerts/new
  def new
    @price_alert = PriceAlert.new
  end

  # GET /price_alerts/1/edit
  def edit
  end

  # POST /price_alerts or /price_alerts.json
  def create
    @price_alert = PriceAlert.new(price_alert_params)

    respond_to do |format|
      if @price_alert.save
        format.html { redirect_to @price_alert, notice: "Price alert was successfully created." }
        format.json { render :show, status: :created, location: @price_alert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @price_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_alerts/1 or /price_alerts/1.json
  def update
    respond_to do |format|
      if @price_alert.update(price_alert_params)
        format.html { redirect_to @price_alert, notice: "Price alert was successfully updated." }
        format.json { render :show, status: :ok, location: @price_alert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @price_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_alerts/1 or /price_alerts/1.json
  def destroy
    @price_alert.destroy
    respond_to do |format|
      format.html { redirect_to price_alerts_url, notice: "Price alert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_alert
      @price_alert = PriceAlert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_alert_params
      params.require(:price_alert).permit(:coin, :currency, :price, :last_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price_alerts/_form.html.erb
<%= form_with(model: price_alert) do |form| %>
  <% if price_alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_alert.errors.count, "error") %> prohibited this price_alert from being saved:</h2>

      <ul>
        <% price_alert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :coin %>
    <%= form.text_field :coin %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :last_price %>
    <%= form.text_field :last_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/price_alerts/edit.html.erb
<h1>Editing Price Alert</h1>

<%= render 'form', price_alert: @price_alert %>

<%= link_to 'Show', @price_alert %> |
<%= link_to 'Back', price_alerts_path %>

app/views/price_alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Price Alerts</h1>

<table>
  <thead>
    <tr>
      <th>Coin</th>
      <th>Currency</th>
      <th>Price</th>
      <th>Last price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_alerts.each do |price_alert| %>
      <tr>
        <td><%= price_alert.coin %></td>
        <td><%= price_alert.currency %></td>
        <td><%= price_alert.price %></td>
        <td><%= price_alert.last_price %></td>
        <td><%= link_to 'Show', price_alert %></td>
        <td><%= link_to 'Edit', edit_price_alert_path(price_alert) %></td>
        <td><%= link_to 'Destroy', price_alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price Alert', new_price_alert_path %>

app/views/price_alerts/new.html.erb
<h1>New Price Alert</h1>

<%= render 'form', price_alert: @price_alert %>

<%= link_to 'Back', price_alerts_path %>

app/views/price_alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coin:</strong>
  <%= @price_alert.coin %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @price_alert.currency %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price_alert.price %>
</p>

<p>
  <strong>Last price:</strong>
  <%= @price_alert.last_price %>
</p>

<%= link_to 'Edit', edit_price_alert_path(@price_alert) %> |
<%= link_to 'Back', price_alerts_path %>